Feature/mail confirmation
IlyaOkonechnikov/emporium pull request #1
Opened 2020-10-24 08:31 UTC by airat-git

2020-10-24 09:06 UTC, IlyaOkonechnikov requested changes

2020-10-24 09:06 UTC, IlyaOkonechnikov commented on auth/src/main/java/com/emporium/auth/service/UserServiceImpl.java
> +    public void mailConfirm(ObjectId id) {
confirmMail

2020-10-24 09:06 UTC, IlyaOkonechnikov commented on auth/src/main/java/com/emporium/auth/service/UserServiceImpl.java
> +    public User findByEmail(String email) {
Удоли

2020-10-24 09:06 UTC, IlyaOkonechnikov commented on auth/src/main/java/com/emporium/auth/controller/AuthController.java
> +    @GetMapping("/mail-confirmation/{id}")
Patch

2020-10-24 10:33 UTC, airat-git commented on auth/src/main/java/com/emporium/auth/config/MailConfirmationConfig.java
> +                                  @Value("${mail.from}")String from,
Habib Case?)

2020-10-25 06:10 UTC, IlyaOkonechnikov commented on auth/src/main/java/com/emporium/auth/config/MailConfirmationConfig.java
> +                                  @Value("${mail.from}")String from,
Habib Win)

2020-10-25 06:13 UTC, IlyaOkonechnikov approved these changes

2020-10-25 06:15 UTC, merged